name: Auto check time

on:

  push:
    branches:
      - master
      
  schedule:
  - cron: "*/2 * * * *" 

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG 
        run: echo "::debug::Ref = ${{github.ref}}"
      - uses: actions/checkout@v3      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_TIME
          
      - name: Commit changes
        run: |
          git config --local user.email "bo50m0xw@gmail.com"
          git config --local user.name "bo50m0xw"
          git add -A
          
          arr[0]="chore(bot): ğŸ˜‚ auto commit check"
          arr[1]="chore(bot): ğŸ˜± auto commit check"
          arr[2]="chore(bot): ğŸ‘¿ auto commit check"
          arr[3]="chore(bot): ğŸ’© auto commit check"
          arr[4]="chore(bot): ğŸ™ auto commit check"
          arr[5]="chore(bot): ğŸ™ˆ auto commit check"
          arr[6]="chore(bot): ğŸ auto commit check"
          arr[7]="chore(bot): ğŸ¤– auto commit check"
          arr[8]="chore(bot): ğŸŸ© auto commit check"
          arr[9]="chore(bot): ğŸ‘» auto commit check"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
